# Funding options for Enterprise AI Platform
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: rogermsc
# ko_fi: goodai
# custom: ['https://www.goodai.com/enterprise']
